### ISSUE TITLE
Is just wiping data after editing

### ISSUE THREAD

**Issue by Tydos-10** [jlcrochet/inscryption_save_editor#19]
Once finished editing a nintendo switch save file, and downloading the output, it just wipes your data after putting it back with checkpoint, removing kaycees mod, the act selector, and forcing you into the intro where luke first opens the game.

i have attached a zip fie with all 3 edited outputs, as well as the unedited input
[Inscryption.Save.File3.17.24.zip](https://github.com/jlcrochet/inscryption_save_editor/files/14627922/Inscryption.Save.File3.17.24.zip)

**Comment by jlcrochet** [comment]
I just fixed a minor bug that may be related to your issue. Please give it another try and let me know what happens.

**Comment by Tydos-10** [comment]
Unfortunately, the update to the code has not fixed the wiping issue.

**Comment by jlcrochet** [comment]
I see, sorry about that. I don't really know anything about how Checkpoint works, so I'm going to have to look into this further. I'll try to get around to it later this week.

**Comment by Tydos-10** [comment]
Thank you!

**Comment by Tydos-10** [comment]
Unfortunately, your new update makes it so that the game will not even make it to the main menu on switch after injecting the save file, it will crash before it makes it.

**Comment by jlcrochet** [comment]
Can you verify that Checkpoint is not making any changes to the file after it is injected? If you're not sure, could you send me a copy of the save file before it is injected and a copy of the save file after it is injected?
